BEGIN TRANSACTION;
CREATE TABLE "Buyers" (
	`Nombre`	TEXT NOT NULL UNIQUE,
	`Index`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Direccion`	TEXT NOT NULL,
	`Telefono`	NUMERIC NOT NULL UNIQUE
);
COMMIT;
