source 'https://rubygems.org'

gem 'rails'
gem 'bcrypt',               '3.1.7'
gem 'faker',                '1.4.2'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'sass'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'chartkick'
gem 'groupdate'
gem 'active_median'
gem 'lazy_high_charts'
gem 'prawn'
gem 'wicked_pdf'
gem 'wkhtmltopdf-installer'
gem 'wkhtmltopdf-binary'
gem 'pdfkit'
gem 'sdoc', group: :doc

group :development, :test do
  gem 'pg'
  gem 'byebug'
  gem 'web-console'
  gem 'spring'
end

group :test do
  gem 'minitest-reporters'
  gem 'mini_backtrace'
  gem 'guard-minitest'
end

group :production do
  gem 'rails_12factor'
  gem 'sqlite3'
end
